
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 36;
  public static final int STRING_LITERAL = 53;
  public static final int MULT = 25;
  public static final int CHAR = 5;
  public static final int GRTEQ = 35;
  public static final int COMMENT = 22;
  public static final int CASE = 14;
  public static final int DOUBLE = 8;
  public static final int GREATER = 34;
  public static final int CONTINUE = 19;
  public static final int INT = 3;
  public static final int PRIGHT = 40;
  public static final int LESS = 32;
  public static final int FOR = 17;
  public static final int MINUS = 24;
  public static final int BOOLEAN_LITERAL = 51;
  public static final int CHARACTER_LITERAL = 52;
  public static final int SEMICOLON = 44;
  public static final int AND = 28;
  public static final int ELSEIF = 12;
  public static final int OR = 29;
  public static final int COMMA = 46;
  public static final int DIV = 26;
  public static final int BLEFT = 43;
  public static final int PLUS = 23;
  public static final int NULL_LITERAL = 55;
  public static final int ASSIGN = 30;
  public static final int LESSEQ = 33;
  public static final int IF = 10;
  public static final int DOT = 47;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int MINUSMINUS = 37;
  public static final int RETURN = 20;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int PLEFT = 41;
  public static final int MOD = 27;
  public static final int NEQ = 31;
  public static final int CONSTANT = 48;
  public static final int BREAK = 18;
  public static final int VOID = 9;
  public static final int EQ = 21;
  public static final int SWITCH = 13;
  public static final int COLON = 45;
  public static final int FLOATING_POINT_LITERAL = 50;
  public static final int ELSE = 11;
  public static final int WHILE = 16;
  public static final int DEFAULT = 15;
  public static final int FLOAT = 7;
  public static final int LONG = 4;
  public static final int STRING = 6;
  public static final int FALSE = 39;
  public static final int BRIGHT = 42;
  public static final int IDENTIFIER = 54;
  public static final int INTEGER_LITERAL = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "INT",
  "LONG",
  "CHAR",
  "STRING",
  "FLOAT",
  "DOUBLE",
  "VOID",
  "IF",
  "ELSE",
  "ELSEIF",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "WHILE",
  "FOR",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "EQ",
  "COMMENT",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "AND",
  "OR",
  "ASSIGN",
  "NEQ",
  "LESS",
  "LESSEQ",
  "GREATER",
  "GRTEQ",
  "PLUSPLUS",
  "MINUSMINUS",
  "TRUE",
  "FALSE",
  "PRIGHT",
  "PLEFT",
  "BRIGHT",
  "BLEFT",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "DOT",
  "CONSTANT",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NULL_LITERAL"
  };
}

